title:              Ponderer's Nook
email:              sakshi.shrivastava1980@gmail.com
description:        My place of musing
author:             Sakshi Shrivastava
baseurl:            "/startbootstrap-clean-blog-jekyll"
url:                "https://github.com/ponderersnook"

# Social Profiles
twitter_username:   
github_username:    ponderersnook
facebook_username:  
instagram_username:  _strawberrylegs
linkedin_username:  sakshi163

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

theme: jekyll-theme-midnight
